CREATE SCHEMA IF NOT EXISTS SA;
SET SCHEMA SA;
CREATE TABLE IF NOT EXISTS PERSON (ID INTEGER PRIMARY KEY, NAME VARCHAR, AGE NUMBER, IQ NUMBER, BIRTHDAY TIMESTAMP);
CREATE TABLE IF NOT EXISTS PERSON_FIELDS (ID INTEGER PRIMARY KEY, NAME VARCHAR, VAL VARCHAR, PERSON_ID INTEGER, foreign key (PERSON_ID) references PERSON(ID));
CREATE TABLE IF NOT EXISTS EMPTY (NAME VARCHAR, VAL NUMBER);
CREATE TABLE IF NOT EXISTS TYPES (ID INTEGER PRIMARY KEY, TIMESTAMP_TYPE TIMESTAMP, DATETIME_TYPE SMALLDATETIME, DATE_TYPE DATE);

CREATE TABLE IF NOT EXISTS androids_table (ID INTEGER PRIMARY KEY, NAME VARCHAR, HEIGHT NUMBER, WEIGHT NUMBER, MANUFACTURED TIMESTAMP);

create table if not exists orders (
    id INTEGER primary key,
    status VARCHAR,
    client number,
    driver number,
    created timestamp,
    updated timestamp
);