# This workflow will build a package using Gradle and then publish it
name: Maven Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: gradle build

      - name: Publish
        run: gradle publishMaven
        env:
          ossrhUsername: ${{ secrets.OSSRHUSERNAME }}
          ossrhPassword: ${{ secrets.OSSRHPASSWORD }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRHUSERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRHPASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}

      - name: Update live specs
        run: sh .utility/update-gh-pages.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}